- hosts: localhost

  vars_files: 
  - details1.yml
 
  tasks: 
  - name: "creating vpc"
    ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "ap-south-1"
        aws_access_key: "{{ aws_ak }}" 
        aws_secret_key: "{{ aws_sk }}"

    register: x

  - name: "launching subnet"
    ec2_vpc_subnet:
        state: present
        vpc_id: "{{ x['vpc']['id'] }}"
        cidr: "{{ item.cidr }}"
        resource_tags:
            Name: "{{ item.subnet_name }}"

    loop: 
    -    { subnet_name: "{{ subnet_name1 }}" , cidr: "{{ subnet_cidr1 }}" }
    -    { subnet_name: "{{ subnet_name2 }}" , cidr: "{{ subnet_cidr2 }}" }
