- hosts: localhost

  vars_files: 
  - details1.yml
 
  tasks: 
  - name: "creating vpc"
    ec2_vpc_net:
        name: "my_vpc1"
        cidr_block: "{{ vpc_cidr }}"
        region: "ap-south-1"
        aws_access_key: "{{ aws_ak }}" 
        aws_secret_key: "{{ aws_sk }}"

    register: x

  - name: "launching subnet"
    ec2_vpc_subnet:
        state: present
        vpc_id: "{{ x['vpc']['id'] }}"
        cidr: "{{ item.cidr }}"
        resource_tags:
            Name: "{{ item.subnet_name }}"

    loop: 
    -    { subnet_name: "mysubnet_1" , cidr: 53.160.101.0/24 }
    -    { subnet_name: "mysubnet_2" , cidr: 53.160.200.0/24 }

