- hosts: localhost

  vars_files: 
  - details1.yml
 
  tasks: 
  - name: "creating vpc"
    ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "ap-south-1"
        aws_access_key: "{{ aws_ak }}" 
        aws_secret_key: "{{ aws_sk }}"

    register: x

  - name: "creating internet gateway"
    ec2_vpc_igw:
        state: present
        vpc_id: "{{ x['vpc']['id'] }}"
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
  
    register: igw

  - name: "launching subnet"
    ec2_vpc_subnet:
        state: present
        az: "ap-south-1a"
        vpc_id: "{{ x['vpc']['id'] }}"
        cidr: "{{ item.cidr }}"
        resource_tags:
            Name: "{{ item.subnet_name }}"

    loop: 
    -   { subnet_name: "{{ subnet_name1 }}" , cidr: "{{ subnet_cidr1 }}" }
    -   { subnet_name: "{{ subnet_name2 }}" , cidr: "{{ subnet_cidr2 }}" }

    register: sub

  - name: "creating route tables"
    ec2_vpc_route_table:
        vpc_id: "{{ x['vpc']['id'] }}"
        region: "ap-south-1"
        routes:
        -   dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        subnets:
        -   "{{ subnet_cidr1 }}"
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
  
  - name: "creating instances..."
    ec2_instance:
        region: "ap-south-1"
        image_id: "ami-0a9d27a9f4f5c0efc"
        instance_type: "t2.micro"
        vpc_subnet_id: "{{ item.sub_id }}"
        key_name: "{{ key }}"
        security_group: "{{ sg_group }}"
        name: "{{ item.instance_name }}"
        state: present
        network:
            assign_public_ip: no
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
        volumes:
        -   device_name: "/dev/sda1"
            ebs:
               volume_size: 10
               delete_on_termination: true
   
    loop:
    -   { instance_name: "{{ instance_name1 }}" , sub_id: "{{ sub['results'][0]['subnet']['id'] }}" }
    -   { instance_name: "{{ instance_name2 }}" , sub_id: "{{ sub['results'][1]['subnet']['id'] }}" }
     

        
        




