---

- hosts: localhost
  vars_files:
  -     sample_vars.yml
  tasks:
  - name: "creating lambda"
    community.aws.lambda:
        name: "testingfunctions3"
        state: present
        s3_bucket: "{{ bucket_name }}"
        s3_key: "{{ package_name }}"
        runtime: "python3.8"
        handler: "sample.myfun"
        region: "ap-south-1"
        role: "{{ arn }}"
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"

