- hosts: all
  vars:
  -  mount_point: /my_mount
  -  doc_root: /var/www/Y
  -  port_no: 581/tcp
      
  tasks:
  - selinux:
      state: disabled

  - file:
      path: "{{ mount_point }}"
      state: directory

  - mount:
      path: "{{ mount_point }}"
      src: "/dev/sr0"
      fstype: iso9660
      state: mounted

  - yum_repository:
      name: "nr1"
      description: "test repo"
      baseurl: "{{ mount_point }}/AppStream"
      gpgcheck: no

  - yum_repository:
      name: "nr2"
      description: "test repo2"
      baseurl: "{{ mount_point }}/BaseOS"
      gpgcheck: no
  
  - package:
      name: "httpd"
      state: present

  - copy :
      src: "/root/new1.conf"
      dest: "/etc/httpd/conf.d"

  - file:
      path: "{{ doc_root }}"
      state: directory

  - copy:
      src: "/root/x.html"
      dest: "{{ doc_root }}"

  - service:
      name: "httpd"
      state: started

  - firewalld:
      port: "{{ port_no }}"
      immediate: yes
      state: enabled


 
