# playbook.yml
---
- hosts: localhost
  connection: local
  vars:
    ip_addresses:
      - <ip1>
      - <ip2>
  tasks:
    - name: deploy files with network address in them
      include_tasks: network_files.yml
      loop: "{{ ip_addresses }}"
