- hosts: localhost
  vars_files:
  -    details.yml

  tasks:
  - ec2_instance:
       region: "ap-south-1"
       image_id: "ami-0a9d27a9f4f5c0efc"
       instance_type: "t2.micro"
       vpc_subnet_id: "{{ vpcsi }}"
       key_name: "{{ key }}"
       security_group: "{{ sg_group }}"
       name: "Backend-Server1"
       state: present
       aws_access_key: "{{ aws_ak }}"
       aws_secret_key: "{{ aws_sk }}"
       volumes:
       - device_name: "/dev/sda1"
         ebs:
           volume_size: 10
           delete_on_termination: true

    register: x

  - lineinfile:
       path: "/root/inven.txt"
       line: "{{ x.instances[0].public_ip_address }}"

  - ec2_instance:
       region: "ap-south-1"
       image_id: "ami-0a9d27a9f4f5c0efc"
       instance_type: "t2.micro"
       vpc_subnet_id: "{{ vpcsi }}"
       key_name: "{{ key }}"
       security_group: "{{ sg_group }}"
       name: "Backend-Server2"
       state: present
       aws_access_key: "{{ aws_ak }}"
       aws_secret_key: "{{ aws_sk }}"
       volumes:
       - device_name: "/dev/sda1"
         ebs:
           volume_size: 10
           delete_on_termination: true

    register: y

  - lineinfile:
       path: "/root/inven.txt"
       line: "{{ y.instances[0].public_ip_address }}"
 
  - wait_for:
       timeout: 300


