- hosts: localhost
  vars_files:
  -    details.yml
  
  tasks:
  - pip:
       name: 'boto3'
 
  - ec2_instance: 
       region: "ap-south-1"
       image_id: "ami-0a9d27a9f4f5c0efc"
       instance_type: "t2.micro"
       vpc_subnet_id: "{{ vpcsi }}"
       key_name: "{{ key }}"
       security_group: "{{ sg_group }}"
       name: "Load-Balancer"
       state: present
       aws_access_key: "{{ aws_ak }}"
       aws_secret_key: "{{ aws_sk }}"
       volumes:
       - device_name: "/dev/sda1"
         ebs:
           volume_size: 10
           delete_on_termination: true
 
    register: x

  - blockinfile:
       path: "/root/inven.txt"
       block: "{{ x.instances[0].public_ip_address }}"  

  - wait_for:
       timeout: 300 
  

  
  








  
