- hosts: localhost
  tasks:
  - name: "launching ec2-instance for load balancer"
    shell:
       cmd: "ansible-playbook awsw.yml"

  - name: "installing haproxy on load balancer"
    shell:
       cmd: "ansible-playbook clb.yml"
