- hosts: load_balancer
  vars_files:
  -     details.yml

  tasks:
  -  file: 
        path: "/etc/haproxy/haproxy.cfg"
        state: absent

  -  template:
        src: "/root/haproxy.cfg"
        dest: "/etc/haproxy"
  
  -  service:
        name: "haproxy"
        state: started
   
