- hosts: "{{ host_ip }}"
  vars_files: 
  -   datanode_vars.yml
  tasks:
  - name: "creating folder"
    file:
      path: "{{ soft_drt }}"
      state: directory

  - copy:
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"
      dest: "{{ soft_drt }}"

  - copy:
      src: "/root/jdk-8u171-linux-x64.rpm"
      dest: "{{ soft_drt }}"

  - name: "installing java"
    yum:
      name: "{{ soft_drt }}/jdk-8u171-linux-x64.rpm"
      state: present
      disable_gpg_check: yes

  - name: "installing hadoop"
    shell: "rpm -i {{ soft_drt }}/hadoop-1.2.1-1.x86_64.rpm --force"


  - name: "copying configuration files"
    template:
      src: "/core-site.xml"
      dest: "/etc/hadoop"

  - name: "copying configuration files"
    template:
      src: "/hdfs-site.xml"
      dest: "/etc/hadoop"

  - file:
      path: "{{ folder_name }}"
      state: directory
 
  - name: "starting datanode"
    shell: "hadoop-daemon.sh start datanode"
