- hosts: "{{ host_ip }}"
  vars_files:
  - namenode_vars.yml
  tasks:
  - name: "creating folder"
    file:
      path: "{{ software_drt }}"
      state: directory

  - copy:
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"
      dest: "{{ software_drt }}"
  
  - copy:
      src: "/root/jdk-8u171-linux-x64.rpm"
      dest: "{{ software_drt }}"
 
  - name: "installing java"
    yum:
      name: "{{ software_drt }}/jdk-8u171-linux-x64.rpm"
      state: present
      disable_gpg_check: yes

  - name: "installing hadoop"
    shell: "rpm -i {{ software_drt }}/hadoop-1.2.1-1.x86_64.rpm --force"

  - name: "copying configuration files"
    template:
      src: "/root/core-site.xml"
      dest: "/etc/hadoop"

  - name: "copying configuration files"
    template:
      src: "/root/hdfs-site.xml"
      dest: "/etc/hadoop"

  - file:
      path: "{{ folder_name }}"
      state: directory

  - name: "formatting namenode"
    shell: "echo 'Y' | hadoop namenode -format"

  - name: "starting namenode"
    shell: "hadoop-daemon.sh start namenode"

  - firewalld:
       port: "{{ port_no }}/tcp"
       state: enabled
  


  

